server.port=8089
spring.application.name=SkyShayma
spring.datasource.url=jdbc:mysql://localhost:3306/Sky?createDatabaseIfNoExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create


